/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "top.v:1" *)
module top(a, b, clk, y);
  (* src = "top.v:1" *)
  wire _0_;
  (* src = "top.v:1" *)
  input a;
  (* src = "top.v:1" *)
  input b;
  (* src = "top.v:1" *)
  input clk;
  (* src = "top.v:1" *)
  wire q;
  (* src = "top.v:1" *)
  output y;
  \$_AND_  _1_ (
    .A(b),
    .B(a),
    .Y(_0_)
  );
  (* src = "top.v:1" *)
  \$_DFF_P_  q_reg /* _2_ */ (
    .C(clk),
    .D(_0_),
    .Q(q)
  );
  assign y = q;
endmodule
